- name: Install pip
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
   - python-pip

- name: Install docker
  pip: 
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
   - { name: docker,    version: 2.0.0}
   - { name: docker-py, version: 1.10.6}

- name: Start docker service, if not running
  service:
    name: docker
    state: started

- name: Download and run petclinic container, if not running
  docker:
    name: petclinic
    image: iamveershukla/petclinic:1.0.0
    state: started
    ports: 8085:8085

- name: Download and run filebeat container, if not running
  docker:
    name: petclinic
    image: iamveershukla/filebeat-petclinic:1.0.0
    state: started
